/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "csiokxaornvrjyfhkwxr"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzaW9reGFvcm52cmp5Zmhrd3hyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcwOTQwNzAsImV4cCI6MjA5MjY3MDA3MH0.7awo-niwPRLu-GML8PSx27OpTAEFcU182PGhk0Q8q_8"